"""Shared fixtures for pylimma tests.

Loads the CSV reference data generated by generate_reference.R into numpy
arrays and makes them available to all test modules via pytest fixtures.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

REF = Path(__file__).parent / "reference_data"


def _load_csv(fname: str) -> np.ndarray:
    return np.loadtxt(REF / fname, delimiter=",")


def _load_scalar(fname: str) -> float:
    return float(np.loadtxt(REF / fname, delimiter=","))


@pytest.fixture(scope="session")
def ref_E() -> np.ndarray:
    return _load_csv("E.csv")


@pytest.fixture(scope="session")
def ref_design() -> np.ndarray:
    return _load_csv("design.csv")


@pytest.fixture(scope="session")
def ref_lmfit_coef() -> np.ndarray:
    return _load_csv("lmfit_coef.csv")


@pytest.fixture(scope="session")
def ref_lmfit_stdev_unscaled() -> np.ndarray:
    return _load_csv("lmfit_stdev_unscaled.csv")


@pytest.fixture(scope="session")
def ref_lmfit_sigma() -> np.ndarray:
    return _load_csv("lmfit_sigma.csv")


@pytest.fixture(scope="session")
def ref_lmfit_df_residual() -> np.ndarray:
    return _load_csv("lmfit_df_residual.csv")


@pytest.fixture(scope="session")
def ref_lmfit_cov_coef() -> np.ndarray:
    return _load_csv("lmfit_cov_coef.csv")


@pytest.fixture(scope="session")
def ref_eb_t() -> np.ndarray:
    return _load_csv("eb_t.csv")


@pytest.fixture(scope="session")
def ref_eb_pvalue() -> np.ndarray:
    return _load_csv("eb_pvalue.csv")


@pytest.fixture(scope="session")
def ref_eb_s2post() -> np.ndarray:
    return _load_csv("eb_s2post.csv")


@pytest.fixture(scope="session")
def ref_eb_df_total() -> np.ndarray:
    return _load_csv("eb_df_total.csv")


@pytest.fixture(scope="session")
def ref_eb_df_prior() -> float:
    return _load_scalar("eb_df_prior.csv")


@pytest.fixture(scope="session")
def ref_eb_s2prior() -> float:
    return _load_scalar("eb_s2prior.csv")


@pytest.fixture(scope="session")
def ref_eb_lods() -> np.ndarray:
    return _load_csv("eb_lods.csv")


@pytest.fixture(scope="session")
def ref_cf_coef() -> np.ndarray:
    return _load_csv("cf_coef.csv")


@pytest.fixture(scope="session")
def ref_cf_stdev_unscaled() -> np.ndarray:
    return _load_csv("cf_stdev_unscaled.csv")


@pytest.fixture(scope="session")
def ref_cf_t() -> np.ndarray:
    return _load_csv("cf_t.csv")


@pytest.fixture(scope="session")
def ref_cf_pvalue() -> np.ndarray:
    return _load_csv("cf_pvalue.csv")
